---
title: "About"
---

Legal.IA es un equipo multidisciplinario de talentos comprometidos en la intersección de la tecnología y el derecho. Construimos sobre sistemas inteligentes con el doble objetivo de democratizar el conocimiento legal y mejorar las capacidades de los profesionales legales. Nuestro trabajo es un compromiso continuo que apunta a hacer el derecho más accesible y manejable para todos. 

En primer lugar, creemos que el derecho, como pilar fundamental de nuestra sociedad, debe ser accesible y comprensible para todos. El campo legal es una esfera que, si bien es esencial para la sociedad, a menudo puede parecer inaccesible para quienes no son expertos. Creemos que la tecnología, y en particular la Inteligencia Artificial, tiene el potencial de cambiar esto. Queremos hacer que el conocimiento legal sea más accesible y comprensible para todos los ciudadanos, bajo la firme creencia de que una sociedad informada es una sociedad más fuerte y justa.

En segundo lugar, buscamos asistir a los trabajadores del campo legal en sus tareas. La carga de trabajo en este sector puede ser abrumadora, y las herramientas basadas en IA pueden contribuir significativamente a aliviarla, permitiendo a estos profesionales centrarse en aspectos más críticos y humanos de su trabajo. Entendemos y respetamos profundamente el valor y la importancia de los trabajadores legales en nuestra sociedad. Su experiencia, conocimiento y habilidad humana son fundamentales para la administración de justicia y la construcción de una sociedad justa. No vemos la tecnología como un reemplazo de trabajadores legales, sino como una oportunidad para fortalecer y ampliar su papel en la sociedad.

Con estas ideas en mente desarrollamos a ALI, el primer Asistente Legal Inteligente de la Argentina. Basado en Modelos de Lenguaje a Gran Escala (LLMs), ALI busca ser una herramienta útil y efectiva tanto para profesionales del derecho como para la sociedad en general. 

A DESARROLLAR -> Compromiso con el trabajo colaborativo y el open-souce --> say no to zero sum games e importancia de la transparencia. 

